### ISSUE TITLE
Include permittivity and absorption coefficient?

### ISSUE THREAD

**Issue by FilipDominec** [polyanskiy/refractiveindex.info-scripts#5]
Hi, since I set up electromagnetic simulations an optical experiments now and then, I found refractiveindex.info quite useful and I was twice as happy to find out it has an open-source project here on github. So at the first place, thank you a lot for your work.

For FDTD simulations, it is usually necessary to supply the permittivity spectrum in the form of a sum of discrete Lorentzian oscillators. An example from my humble material library is here: https://github.com/FilipDominec/python-meep-utils/blob/master/meep_materials.py

To make sure the models are realistic, I have set up as many sources of permittivity (or at least refractive index) spectra as I could, and compared these on a static web page http://www.fzu.cz/~dominecf/eps/index.html

Do you think such a functionality could be added to refractiveindex.info, so that one could 
1) visualize also the permittivity and absorption coefficient,
2) possibly download a table of Lorentz oscillators describing these spectra, where available,
2) and also compare the presented curve with experimental data from multiple sources, as it is on the ~dominecf/eps website?

**Comment by FilipDominec** [comment]
Note that the plotting script at http://www.fzu.cz/~dominecf/eps/data/plot_eps.zip also contains (rather nontrivial) parsers for 
1) reading ```*.b``` files from the SCOUT database (at http://www.wtheiss.com/download/scout.zip)
2) reading ```*.MAT``` files from the SOPRA database (at http://sspectra.com/sopra.html)

**Comment by polyanskiy** [comment]
Hi Filip,
you did a great job putting together all the models! And I like how you organized the material and scripts.
I think however that such functionality is probably beyond the scope of refractiveindex.info database and the associated website. What I am trying to do is to collect and organize data, rather than analyzing and interpreting it.
