### ISSUE TITLE
Refractive index calculation in UBUNTU 16.04.4

### ISSUE THREAD

**Issue by hazraatrayee** [polyanskiy/refractiveindex.info-scripts#8]
I have downloaded the package 'refractiveindex.info-scripts-master". When I am trying to run the program by giving the command python ldbb.py, while positioned in ldbb, there is showing some error as mentioned below.

dell@dell-OptiPlex-3050:~/refractiveindex.info-scripts-master/ldbb$ python ldbb.py
Traceback (most recent call last):
  File "ldbb.py", line 29, in <module>
    from scipy import constants
ImportError: No module named scipy

Could you please help me to solve this problem.

**Comment by FilipDominec** [comment]
```scipy``` is a common module for scientific computing in Python. If you have Ubuntu, you can install it by running ```sudo apt-get install python-scipy```.

**Comment by hazraatrayee** [comment]
when this command is used what i am getting is:

root@dell-OptiPlex-3050:~# sudo apt-get install python-scipy
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?


Now what should i do?

**Comment by FilipDominec** [comment]
Dear hazraatrayee, this error is completely unrelated to the *refractiveindex.info-scripts*. Please search the ubuntu help/forums to find the solution.

**Comment by hazraatrayee** [comment]
Ok, Thank you.
